### ISSUE TITLE
static mut code in blog post

### ISSUE THREAD

**Issue by troublescooter** [rust-secure-code/safety-dance#72]
[Here](https://github.com/pretzelhammer/rust-blog/issues/19) I pointed out that the use of `static mut` might be ill-advised, since there seemed to be a lot of fine-print involved in using it correctly (linked in the issue).
With the introduction of const-generic indexing I thought to revisit the issue and was asked to provide stronger arguments for my concerns.

I admit to not being sufficiently proficient to make a strong case, and upon rereading the linked posts in the issue some confusion remains:

In [unsafe statics](https://github.com/withoutboats/rfcs/blob/unsafe-statics/text/0000-unsafe-statics.md) withoutboats states

> Actually taking a mutable reference is unsafe. However, this feature is incredibly footgunny and almost impossible to use correctly, since creating a mutable reference to shared memory is undefined behavior, even if you never dereference that reference.

Is `&mut` on `static mut` considered shared, even if not used in a multithreaded context? [This answer](https://www.reddit.com/r/rust/comments/bkw00l/why_is_static_mut_bad_to_use/emthudq/) from eddyb suggests that is the case, although the comment is not crystal-clear in a way that would be helpful to me. Concurrency being feasible in other contexts than the multithreaded case does not mean all cases of `&mut` on `static mut` is UB (*edit: outside a `Cell` or `RefCell`). I would think removing such an example from a blog post aimed at beginners would be worthwhile nonetheless, but I have been asked to prove the trivial code snippet is indeed UB, and MIRI is silent on the issue.

The code in question is

```
static mut MUT_BYTES: [u8; 3] = [1, 2, 3];
fn main() {
    unsafe {
        MUT_BYTES[0] = 99;
    }
}
```
which with const-generic indexing seems equivalent to
```
static mut MUT_BYTE: u8 = 1;
fn main() {
    unsafe {
        let ptr = &mut MUT_BYTE;
        *ptr = 99;
    }
}
```
Is this UB?

**Comment by danielhenrymantilla** [comment]
That pattern isn't UB _per se_, although the _global_ `static mut` makes it error-prone in general. In that example, I'd prefer if, given:
```rust
macro_rules! once {( $($code:tt)* ) => (
    {
        use ::std::sync::Once;
        static O: Once = Once::new();
        &O
    }.call_once(|| { $($code)* })
)}
```
it was:
```rust
fn main ()
{
    once! {
        let ptr = unsafe { static mut MUT_BYTE: u8 = 1; &mut MUT_BYTE };
        *ptr = 99;
    }
}
```

That way we do have a snippet that is robust to getting code added onto it.

___

The issue of `static mut THING: T = …`, _vs._ using its less error-prone `static THING: RacyCell<T> = RacyCell::new(…);` alternative, is conceptually similar to using `mem::unitialized()` _vs._ using `MaybeUninit::uninit()`-followed by-`.assume_init()` later on: in both cases, with the latter pattern, we avoid making the strong assumption to early to be correct. In the case of a `static mut` and a `static RacyCell`, the latter allows aliasing pointers with interleaved mutations whereas the former does not:

```rust
once! {
  static THING: RacyCell<T> = RacyCell::new(…);

  let ptr1: *mut T = THING.get(); // SB: shared read-write
  let ptr2: *mut T = THING.get(); // SB: shared read-write
  unsafe {
      (&mut *ptr1).mutate(); // SB: temporarily upgrade to unique
      (&mut *ptr2).mutate(); // ditto
      (&mut *ptr1).mutate();
      (&mut *ptr2).mutate();
  }
}
```
whereas the following is UB:
```rust
once! {
  static mut THING: T = …;
  unsafe {
      let ptr1: *mut T = &mut THING; // SB: shared read-write *derived from unique* (OK)
      let ptr2: *mut T = &mut THING; // SB: shared read-write *derived from unique* (Invalidates ptr1)
      (&mut *ptr1).mutate(); // UB: usage of invalidated pointer
      …
  }
}
```

Notice how getting a raw mutable (SB: shared read-write) pointer to the global is not unsafe and thus not unsound with a `static RacyCell`, whereas even just forging such a raw pointer with a `static mut` is `unsafe` and thus UB-prone, since it does require / assert unicity of the access to the global (whereas with `RacyCell` we only make the unicity assertion on actual dereference of that pointer).

**Comment by troublescooter** [comment]
Thanks for the detailed elaboration!
